

```{r}
d10 <- rownames(meta[meta$days == "D10",])
print(length(d10))
d3 <- meta[meta$days == "D03",] %>% 
  sample_n(size = length(d10), replace = FALSE) %>%
  rownames()
print(length(d3))
  
d7 <- meta[meta$days == "D07",] %>% 
  sample_n(size = length(d10), replace = FALSE) %>%
  rownames()
print(length(d7))

to.keep <- c(d3, d7, d10)
sub.obj2 <- subset(sub.obj, cells = to.keep)
```

# downsample sars POS
```{r}
pos <- rownames(meta[meta$sars.pos == "POS", ]) 
neg <- meta[meta$sars.pos == "NEG", ] %>%
  sample_n(size = length(pos), replace = FALSE) %>%
  rownames()
to.keep <- c(neg, pos)

down.obj <- subset(sub.obj, cells = to.keep)
DimPlot(down.obj, pt.size = 1, group.by = "predicted.celltype", split.by = "sars.pos")
ggsave(filename = "all_virus/downsample_sars_umap.pdf", width = 9)
```
# downsample for Omicron
```{r}
pos <- rownames(meta[meta$is.Omicron == "Omicron", ]) 
neg <- meta[meta$is.Omicron == "Others", ] %>%
  sample_n(size = length(pos), replace = FALSE) %>%
  rownames()
to.keep <- c(neg, pos)

down.obj <- subset(sub.obj, cells = to.keep)
DimPlot(down.obj, group.by = "predicted.celltype", split.by = "is.Omicron")
ggsave(filename = "all_virus/downsample_OmicronVsOthers_umap.pdf", width = 9)
```


# perform DE by days
It usually recommend using "RNA"assay, However, Seurat also say SCT could do this purpose
# perform DE using SCT data
# MM is interested in export 100 DE for each cell types
# here I changed the seurat_clusters to the value of celltype, save a copy of it at the same time

```{r}
DefaultAssay(sub.obj) <- "SCT"
sub.obj[["seurat_clusters_old"]] <- sub.obj$seurat_clusters
sub.obj[["seurat_clusters"]] <- sub.obj$predicted.celltype
#sub.obj <- PrepSCTFindMarkers(object = sub.obj)?????
markers <- FindAllMarkers(sub.obj)
write.csv(markers, file = paste0(run.name, "/", format(Sys.Date(), "%Y-%m-%d"), "-", "marker_genes_by_celltype.csv"))
top100 <- markers %>%
    group_by(cluster) %>%
    slice_max(n = 100, order_by = avg_log2FC)
write.csv(top100, file = paste0(run.name, "/", format(Sys.Date(), "%Y-%m-%d"), "-", "top100_genes_by_celltype.csv"))
```


```{r}
Idents(sub.obj) <- sub.obj$days
sub.obj <- PrepSCTFindMarkers(object = sub.obj) # takes about 1 h
```
